# Generated by Django 6.0 on 2026-01-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='priority',
        ),
    ]
